### ISSUE TITLE
config

### ISSUE THREAD

**Issue by agentJames** [tonymorris/MMM-lichess-daily#5]
Are the lines you put into the config.js correct, because when I put it in I get a "please create a config file"?

**Comment by tonymorris** [comment]
Which lines are you referring to?

**Comment by agentJames** [comment]
Thank you for responding, I am a little new to this so I don't know how to fix this. I think I am forgetting to write something.
I can not get the picture of the whole code to show but what I wrote was all the lines you told to write in the config.js file with that, below module and on top of config I wrote "position: "top_right",".

So my overall question is what am I suppose to do so the config file error does not show up?

**Comment by agentJames** [comment]
Just as a side note all the lines means from {disabled: false, to 60 * 1000; } },

**Comment by tonymorris** [comment]
This is the relevation portion of my `config/config.js` file:

```
{
      module: "MMM-lichess-daily",
      disabled: false,
      position: "top_left",
      config: {
        theme: "blue3",
        bg: "dark",
        width: "246px",
        height: "290px",
      }
    },
```

**Comment by agentJames** [comment]
Thank you for the quick response it works now. I saw that there is another issue listed which is a little the same as what I am going to say. When I click it goes to full screen, once I am done with the puzzle how do I go back to the original page? I am not using a touch screen like the other person.

**Comment by tonymorris** [comment]
I'm really not sure. I don't use any clicking or touch-screen, only display.

**Comment by agentJames** [comment]
According to what you said, I am just wondering, is this module just suppose to show what the current daily puzzle is? We are not really suppose to click it.

**Comment by agentJames** [comment]
This will most likely be the last question I am going to ask before I close it.

**Comment by tonymorris** [comment]
That's what I use it for. Any improvements are welcome of course.

**Comment by agentJames** [comment]
Thank you for answering everything I asked especially in 1 day. If it looks like I asked a lot, that is because it is my first time doing a "new issue" thing.
